apiVersion: v1
kind: Service
metadata:
        name: ns-service
        labels:
                app: ns
spec:
        ports: 
        - port: 80
          targetPort: 3000
        type: LoadBalancer
        selector:
                app: ns
